export const NOTES = {
  UPDATE_ALL: 'UPDATE_ALL_NOTES',
  UPDATE_ONE: 'UPDATE_ONE_NOTE',
  REMOVE: 'REMOVE_NOTE',
};

export const LABELS = {
  UPDATE_ALL: 'UPDATE_ALL_NOTES',
  UPDATE_ONE: 'UPDATE_ONE_NOTE',
  REMOVE: 'REMOVE_NOTE',
};
