export const NOTES = {
  UPDATE_ALL: 'UPDATE_ALL_NOTES',
  UPDATE_ONE: 'UPDATE_ONE_NOTE',
  REMOVE: 'REMOVE_NOTE',
};

export const LABEL = {
  UPDATE_ALL: 'UPDATE_ALL_LABELS',
  UPDATE_ONE: 'UPDATE_ONE_LABEL',
  REMOVE: 'REMOVE_LABEL',
};
